package com.example.cosc330project1;

import android.graphics.Color;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import java.util.ArrayList;

public class WordSearchFragment extends Fragment {
    TextView t13;
    TextView t14;
    TextView t15;
    TextView t16;
    TextView t17;
    TextView t18;
    TextView t19;
    TextView t20;
    TextView t21;
    TextView t22;
    TextView t23;
    TextView t24;
    TextView t25;
    TextView t26;
    TextView t27;
    TextView t28;
    TextView t29;
    TextView t30;
    TextView t31;
    TextView t32;
    TextView t33;
    TextView t34;
    TextView t35;
    TextView t36;
    TextView t37;
    TextView t38;
    TextView t39;
    TextView t40;
    TextView t41;
    TextView t42;
    TextView t43;
    TextView t44;
    TextView t45;
    TextView t46;
    TextView t47;
    TextView t48;
    TextView t49;
    TextView t50;
    TextView t51;
    TextView t52;
    TextView t53;
    TextView t54;
    TextView t55;
    TextView t56;
    TextView t57;
    TextView t58;
    TextView t59;
    TextView t60;
    TextView t61;
    TextView t62;
    TextView t63;
    TextView t64;
    TextView t65;
    TextView t66;
    TextView t67;
    TextView t68;
    TextView t69;
    TextView t70;
    TextView t71;
    TextView t72;
    TextView t73;
    TextView t74;
    TextView t75;
    TextView t76;
    TextView t77;
    TextView t78;
    TextView t79;
    TextView t80;
    TextView t81;
    TextView t82;
    TextView t83;
    TextView t84;
    TextView t85;
    TextView t86;
    TextView t87;
    TextView t88;
    TextView t89;
    TextView t90;
    TextView t91;
    TextView t92;
    TextView t93;
    TextView t94;
    TextView t95;
    TextView t96;
    TextView t97;
    TextView t98;
    TextView t99;
    TextView t100;
    TextView t101;
    TextView t102;
    TextView t103;
    TextView t104;
    TextView t105;
    TextView t106;
    TextView t107;
    TextView t108;
    TextView t109;
    TextView t110;
    TextView t111;
    TextView t112;
    TextView t113;
    TextView t114;
    TextView t115;
    TextView t116;
    TextView t117;
    TextView t118;
    TextView t119;
    TextView t120;
    TextView t121;
    TextView t122;
    TextView t123;
    TextView t124;
    TextView t125;
    TextView t126;
    TextView t127;
    TextView t128;
    TextView t129;
    TextView t130;
    TextView t131;
    TextView t132;
    TextView t133;
    TextView t134;
    TextView t135;
    TextView t136;
    TextView t137;
    TextView t138;
    TextView t139;
    TextView t140;
    TextView t141;
    TextView t142;
    TextView t143;
    TextView t144;
    TextView t145;
    TextView t146;
    TextView t147;
    TextView t148;
    TextView t149;
    TextView t150;
    TextView t151;
    TextView t152;
    TextView t153;
    TextView t154;
    TextView t155;
    TextView t156;
    TextView t157;
    TextView t158;
    TextView t159;
    TextView t160;
    TextView t161;
    TextView t162;
    TextView t163;
    TextView t164;
    TextView t165;
    TextView t166;
    TextView t167;
    TextView t168;
    TextView t169;
    TextView t170;
    TextView t171;
    TextView t172;
    TextView t173;
    TextView t174;
    TextView t175;
    TextView t176;
    TextView t177;
    TextView t178;
    TextView t179;
    TextView t180;
    TextView t181;
    TextView t182;
    TextView t183;
    TextView t184;
    TextView t185;
    TextView t186;
    TextView t187;
    TextView t188;
    TextView t189;
    TextView t190;
    TextView t191;
    TextView t192;
    TextView t193;
    TextView t194;
    TextView t195;
    TextView t196;
    TextView t197;
    TextView t198;
    TextView t199;
    TextView t200;
    TextView t201;
    TextView t202;
    TextView t203;
    TextView t204;
    TextView t205;
    TextView t206;
    TextView t207;

    TextView t2;
    TextView t3;
    TextView t4;
    TextView t5;
    TextView t6;
    TextView t7;
    TextView t8;
    TextView t9;
    TextView t10;

    ArrayList<View> views;
    ArrayList<View> text;
    String[] words;
    String temp;
    boolean boo;
    boolean flag;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.word_search_fragment, container, false);
        boo = true;
        flag = false;
        temp = "";
        words = new String[]{"Appointment","Copay","Insurance","Breathe","Cough","Interpreter","Checkup","Emergency","Patient"};
        views = new ArrayList<>();
        text = new ArrayList<>();
        t2 = (TextView)view.findViewById(R.id.textView2);
        t3 = (TextView)view.findViewById(R.id.textView3);
        t4 = (TextView)view.findViewById(R.id.textView4);
        t5 = (TextView)view.findViewById(R.id.textView5);
        t6 = (TextView)view.findViewById(R.id.textView6);
        t7 = (TextView)view.findViewById(R.id.textView7);
        t8 = (TextView)view.findViewById(R.id.textView8);
        t9 = (TextView)view.findViewById(R.id.textView9);
        t10 = (TextView)view.findViewById(R.id.textView10);
        text.add(t2);
        text.add(t3);
        text.add(t4);
        text.add(t5);
        text.add(t6);
        text.add(t7);
        text.add(t8);
        text.add(t9);
        text.add(t10);
        t13 = (TextView)view.findViewById(R.id.textView13);
        t13.setOnTouchListener(listener);
        t14 = (TextView)view.findViewById(R.id.textView14);
        t14.setOnTouchListener(listener);
        t15 = (TextView)view.findViewById(R.id.textView15);
        t15.setOnTouchListener(listener);
        t16 = (TextView)view.findViewById(R.id.textView16);
        t16.setOnTouchListener(listener);
        t17 = (TextView)view.findViewById(R.id.textView17);
        t17.setOnTouchListener(listener);
        t18 = (TextView)view.findViewById(R.id.edit1);
        t18.setOnTouchListener(listener);
        t19 = (TextView)view.findViewById(R.id.textView19);
        t19.setOnTouchListener(listener);
        t20 = (TextView)view.findViewById(R.id.textView20);
        t20.setOnTouchListener(listener);
        t21 = (TextView)view.findViewById(R.id.textView21);
        t21.setOnTouchListener(listener);
        t22 = (TextView)view.findViewById(R.id.textView22);
        t22.setOnTouchListener(listener);
        t23 = (TextView)view.findViewById(R.id.textView23);
        t23.setOnTouchListener(listener);
        t24 = (TextView)view.findViewById(R.id.textView24);
        t24.setOnTouchListener(listener);
        t25 = (TextView)view.findViewById(R.id.textView25);
        t25.setOnTouchListener(listener);
        t26 = (TextView)view.findViewById(R.id.textView26);
        t26.setOnTouchListener(listener);
        t27 = (TextView)view.findViewById(R.id.textView27);
        t27.setOnTouchListener(listener);
        t28 = (TextView)view.findViewById(R.id.textView28);
        t28.setOnTouchListener(listener);
        t29 = (TextView)view.findViewById(R.id.textView29);
        t29.setOnTouchListener(listener);
        t30 = (TextView)view.findViewById(R.id.textView30);
        t30.setOnTouchListener(listener);
        t31 = (TextView)view.findViewById(R.id.textView31);
        t31.setOnTouchListener(listener);
        t32 = (TextView)view.findViewById(R.id.textView32);
        t32.setOnTouchListener(listener);
        t33 = (TextView)view.findViewById(R.id.edit2);
        t33.setOnTouchListener(listener);
        t34 = (TextView)view.findViewById(R.id.textView34);
        t34.setOnTouchListener(listener);
        t35 = (TextView)view.findViewById(R.id.textView35);
        t35.setOnTouchListener(listener);
        t36 = (TextView)view.findViewById(R.id.textView36);
        t36.setOnTouchListener(listener);
        t37 = (TextView)view.findViewById(R.id.textView37);
        t37.setOnTouchListener(listener);
        t38 = (TextView)view.findViewById(R.id.textView38);
        t38.setOnTouchListener(listener);
        t39 = (TextView)view.findViewById(R.id.textView39);
        t39.setOnTouchListener(listener);
        t40 = (TextView)view.findViewById(R.id.textView40);
        t40.setOnTouchListener(listener);
        t41 = (TextView)view.findViewById(R.id.textView41);
        t41.setOnTouchListener(listener);
        t42 = (TextView)view.findViewById(R.id.textView42);
        t42.setOnTouchListener(listener);
        t43 = (TextView)view.findViewById(R.id.edit32);
        t43.setOnTouchListener(listener);
        t44 = (TextView)view.findViewById(R.id.textView44);
        t44.setOnTouchListener(listener);
        t45 = (TextView)view.findViewById(R.id.textView45);
        t45.setOnTouchListener(listener);
        t46 = (TextView)view.findViewById(R.id.textView46);
        t46.setOnTouchListener(listener);
        t47 = (TextView)view.findViewById(R.id.textView47);
        t47.setOnTouchListener(listener);
        t48 = (TextView)view.findViewById(R.id.edit3);
        t48.setOnTouchListener(listener);
        t49 = (TextView)view.findViewById(R.id.textView49);
        t49.setOnTouchListener(listener);
        t50 = (TextView)view.findViewById(R.id.textView50);
        t50.setOnTouchListener(listener);
        t51 = (TextView)view.findViewById(R.id.textView51);
        t51.setOnTouchListener(listener);
        t52 = (TextView)view.findViewById(R.id.textView52);
        t52.setOnTouchListener(listener);
        t53 = (TextView)view.findViewById(R.id.textView53);
        t53.setOnTouchListener(listener);
        t54 = (TextView)view.findViewById(R.id.textView54);
        t54.setOnTouchListener(listener);
        t55 = (TextView)view.findViewById(R.id.textView55);
        t55.setOnTouchListener(listener);
        t56 = (TextView)view.findViewById(R.id.edit25);
        t56.setOnTouchListener(listener);
        t57 = (TextView)view.findViewById(R.id.textView57);
        t57.setOnTouchListener(listener);
        t58 = (TextView)view.findViewById(R.id.edit33);
        t58.setOnTouchListener(listener);
        t59 = (TextView)view.findViewById(R.id.textView59);
        t59.setOnTouchListener(listener);
        t60 = (TextView)view.findViewById(R.id.textView60);
        t60.setOnTouchListener(listener);
        t61 = (TextView)view.findViewById(R.id.textView61);
        t61.setOnTouchListener(listener);
        t62 = (TextView)view.findViewById(R.id.edit9);
        t62.setOnTouchListener(listener);
        t63 = (TextView)view.findViewById(R.id.edit4);
        t63.setOnTouchListener(listener);
        t64 = (TextView)view.findViewById(R.id.edit10);
        t64.setOnTouchListener(listener);
        t65 = (TextView)view.findViewById(R.id.edit11);
        t65.setOnTouchListener(listener);
        t66 = (TextView)view.findViewById(R.id.edit12);
        t66.setOnTouchListener(listener);
        t67 = (TextView)view.findViewById(R.id.edit13);
        t67.setOnTouchListener(listener);
        t68 = (TextView)view.findViewById(R.id.edit14);
        t68.setOnTouchListener(listener);
        t69 = (TextView)view.findViewById(R.id.edit15);
        t69.setOnTouchListener(listener);
        t70 = (TextView)view.findViewById(R.id.edit16);
        t70.setOnTouchListener(listener);
        t71 = (TextView)view.findViewById(R.id.edit17);
        t71.setOnTouchListener(listener);
        t72 = (TextView)view.findViewById(R.id.edit18);
        t72.setOnTouchListener(listener);
        t73 = (TextView)view.findViewById(R.id.edit19);
        t73.setOnTouchListener(listener);
        t74 = (TextView)view.findViewById(R.id.edit20);
        t74.setOnTouchListener(listener);
        t75 = (TextView)view.findViewById(R.id.textView75);
        t75.setOnTouchListener(listener);
        t76 = (TextView)view.findViewById(R.id.textView76);
        t76.setOnTouchListener(listener);
        t77 = (TextView)view.findViewById(R.id.textView77);
        t77.setOnTouchListener(listener);
        t78 = (TextView)view.findViewById(R.id.edit5);
        t78.setOnTouchListener(listener);
        t79 = (TextView)view.findViewById(R.id.textView79);
        t79.setOnTouchListener(listener);
        t80 = (TextView)view.findViewById(R.id.textView80);
        t80.setOnTouchListener(listener);
        t81 = (TextView)view.findViewById(R.id.edit21);
        t81.setOnTouchListener(listener);
        t82 = (TextView)view.findViewById(R.id.textView82);
        t82.setOnTouchListener(listener);
        t83 = (TextView)view.findViewById(R.id.textView83);
        t83.setOnTouchListener(listener);
        t84 = (TextView)view.findViewById(R.id.textView84);
        t84.setOnTouchListener(listener);
        t85 = (TextView)view.findViewById(R.id.textView85);
        t85.setOnTouchListener(listener);
        t86 = (TextView)view.findViewById(R.id.edit26);
        t86.setOnTouchListener(listener);
        t87 = (TextView)view.findViewById(R.id.textView87);
        t87.setOnTouchListener(listener);
        t88 = (TextView)view.findViewById(R.id.edit34);
        t88.setOnTouchListener(listener);
        t89 = (TextView)view.findViewById(R.id.textView89);
        t89.setOnTouchListener(listener);
        t90 = (TextView)view.findViewById(R.id.textView90);
        t90.setOnTouchListener(listener);
        t91 = (TextView)view.findViewById(R.id.textView91);
        t91.setOnTouchListener(listener);
        t92 = (TextView)view.findViewById(R.id.textView92);
        t92.setOnTouchListener(listener);
        t93 = (TextView)view.findViewById(R.id.edit6);
        t93.setOnTouchListener(listener);
        t94 = (TextView)view.findViewById(R.id.textView94);
        t94.setOnTouchListener(listener);
        t95 = (TextView)view.findViewById(R.id.textView95);
        t95.setOnTouchListener(listener);
        t96 = (TextView)view.findViewById(R.id.edit22);
        t96.setOnTouchListener(listener);
        t97 = (TextView)view.findViewById(R.id.textView97);
        t97.setOnTouchListener(listener);
        t98 = (TextView)view.findViewById(R.id.edit42);
        t98.setOnTouchListener(listener);
        t99 = (TextView)view.findViewById(R.id.textView99);
        t99.setOnTouchListener(listener);
        t100 = (TextView)view.findViewById(R.id.textView100);
        t100.setOnTouchListener(listener);
        t101 = (TextView)view.findViewById(R.id.edit27);
        t101.setOnTouchListener(listener);
        t102 = (TextView)view.findViewById(R.id.textView102);
        t102.setOnTouchListener(listener);
        t103 = (TextView)view.findViewById(R.id.edit35);
        t103.setOnTouchListener(listener);
        t104 = (TextView)view.findViewById(R.id.textView104);
        t104.setOnTouchListener(listener);
        t105 = (TextView)view.findViewById(R.id.textView105);
        t105.setOnTouchListener(listener);
        t106 = (TextView)view.findViewById(R.id.textView106);
        t106.setOnTouchListener(listener);
        t107 = (TextView)view.findViewById(R.id.textView107);
        t107.setOnTouchListener(listener);
        t108 = (TextView)view.findViewById(R.id.edit7);
        t108.setOnTouchListener(listener);
        t109 = (TextView)view.findViewById(R.id.textView109);
        t109.setOnTouchListener(listener);
        t110 = (TextView)view.findViewById(R.id.textView110);
        t110.setOnTouchListener(listener);
        t111 = (TextView)view.findViewById(R.id.edit23);
        t111.setOnTouchListener(listener);
        t112 = (TextView)view.findViewById(R.id.textView112);
        t112.setOnTouchListener(listener);
        t113 = (TextView)view.findViewById(R.id.edit43);
        t113.setOnTouchListener(listener);
        t114 = (TextView)view.findViewById(R.id.textView114);
        t114.setOnTouchListener(listener);
        t115 = (TextView)view.findViewById(R.id.edit39);
        t115.setOnTouchListener(listener);
        t116 = (TextView)view.findViewById(R.id.edit28);
        t116.setOnTouchListener(listener);
        t117 = (TextView)view.findViewById(R.id.edit40);
        t117.setOnTouchListener(listener);
        t118 = (TextView)view.findViewById(R.id.edit36);
        t118.setOnTouchListener(listener);
        t119 = (TextView)view.findViewById(R.id.edit41);
        t119.setOnTouchListener(listener);
        t120 = (TextView)view.findViewById(R.id.textView120);
        t120.setOnTouchListener(listener);
        t121 = (TextView)view.findViewById(R.id.textView121);
        t121.setOnTouchListener(listener);
        t122 = (TextView)view.findViewById(R.id.textView122);
        t122.setOnTouchListener(listener);
        t123 = (TextView)view.findViewById(R.id.edit8);
        t123.setOnTouchListener(listener);
        t124 = (TextView)view.findViewById(R.id.textView124);
        t124.setOnTouchListener(listener);
        t125 = (TextView)view.findViewById(R.id.textView125);
        t125.setOnTouchListener(listener);
        t126 = (TextView)view.findViewById(R.id.edit24);
        t126.setOnTouchListener(listener);
        t127 = (TextView)view.findViewById(R.id.textView127);
        t127.setOnTouchListener(listener);
        t128 = (TextView)view.findViewById(R.id.edit44);
        t128.setOnTouchListener(listener);
        t129 = (TextView)view.findViewById(R.id.textView129);
        t129.setOnTouchListener(listener);
        t130 = (TextView)view.findViewById(R.id.textView130);
        t130.setOnTouchListener(listener);
        t131 = (TextView)view.findViewById(R.id.edit29);
        t131.setOnTouchListener(listener);
        t132 = (TextView)view.findViewById(R.id.textView132);
        t132.setOnTouchListener(listener);
        t133 = (TextView)view.findViewById(R.id.edit37);
        t133.setOnTouchListener(listener);
        t134 = (TextView)view.findViewById(R.id.textView134);
        t134.setOnTouchListener(listener);
        t135 = (TextView)view.findViewById(R.id.textView135);
        t135.setOnTouchListener(listener);
        t136 = (TextView)view.findViewById(R.id.textView136);
        t136.setOnTouchListener(listener);
        t137 = (TextView)view.findViewById(R.id.textView137);
        t137.setOnTouchListener(listener);
        t138 = (TextView)view.findViewById(R.id.textView138);
        t138.setOnTouchListener(listener);
        t139 = (TextView)view.findViewById(R.id.textView139);
        t139.setOnTouchListener(listener);
        t140 = (TextView)view.findViewById(R.id.textView140);
        t140.setOnTouchListener(listener);
        t141 = (TextView)view.findViewById(R.id.textView141);
        t141.setOnTouchListener(listener);
        t142 = (TextView)view.findViewById(R.id.edit48);
        t142.setOnTouchListener(listener);
        t143 = (TextView)view.findViewById(R.id.edit45);
        t143.setOnTouchListener(listener);
        t144 = (TextView)view.findViewById(R.id.edit49);
        t144.setOnTouchListener(listener);
        t145 = (TextView)view.findViewById(R.id.edit50);
        t145.setOnTouchListener(listener);
        t146 = (TextView)view.findViewById(R.id.edit30);
        t146.setOnTouchListener(listener);
        t147 = (TextView)view.findViewById(R.id.edit51);
        t147.setOnTouchListener(listener);
        t148 = (TextView)view.findViewById(R.id.edit38);
        t148.setOnTouchListener(listener);
        t149 = (TextView)view.findViewById(R.id.edit52);
        t149.setOnTouchListener(listener);
        t150 = (TextView)view.findViewById(R.id.textView150);
        t150.setOnTouchListener(listener);
        t151 = (TextView)view.findViewById(R.id.textView151);
        t151.setOnTouchListener(listener);
        t152 = (TextView)view.findViewById(R.id.textView152);
        t152.setOnTouchListener(listener);
        t153 = (TextView)view.findViewById(R.id.textView153);
        t153.setOnTouchListener(listener);
        t154 = (TextView)view.findViewById(R.id.textView154);
        t154.setOnTouchListener(listener);
        t155 = (TextView)view.findViewById(R.id.textView155);
        t155.setOnTouchListener(listener);
        t156 = (TextView)view.findViewById(R.id.textView156);
        t156.setOnTouchListener(listener);
        t157 = (TextView)view.findViewById(R.id.textView157);
        t157.setOnTouchListener(listener);
        t158 = (TextView)view.findViewById(R.id.edit46);
        t158.setOnTouchListener(listener);
        t159 = (TextView)view.findViewById(R.id.textView159);
        t159.setOnTouchListener(listener);
        t160 = (TextView)view.findViewById(R.id.textView160);
        t160.setOnTouchListener(listener);
        t161 = (TextView)view.findViewById(R.id.edit31);
        t161.setOnTouchListener(listener);
        t162 = (TextView)view.findViewById(R.id.textView162);
        t162.setOnTouchListener(listener);
        t163 = (TextView)view.findViewById(R.id.textView163);
        t163.setOnTouchListener(listener);
        t164 = (TextView)view.findViewById(R.id.textView164);
        t164.setOnTouchListener(listener);
        t165 = (TextView)view.findViewById(R.id.textView165);
        t165.setOnTouchListener(listener);
        t166 = (TextView)view.findViewById(R.id.textView166);
        t166.setOnTouchListener(listener);
        t167 = (TextView)view.findViewById(R.id.textView167);
        t167.setOnTouchListener(listener);
        t168 = (TextView)view.findViewById(R.id.textView168);
        t168.setOnTouchListener(listener);
        t169 = (TextView)view.findViewById(R.id.textView169);
        t169.setOnTouchListener(listener);
        t170 = (TextView)view.findViewById(R.id.textView170);
        t170.setOnTouchListener(listener);
        t171 = (TextView)view.findViewById(R.id.textView171);
        t171.setOnTouchListener(listener);
        t172 = (TextView)view.findViewById(R.id.textView172);
        t172.setOnTouchListener(listener);
        t173 = (TextView)view.findViewById(R.id.edit47);
        t173.setOnTouchListener(listener);
        t174 = (TextView)view.findViewById(R.id.textView174);
        t174.setOnTouchListener(listener);
        t175 = (TextView)view.findViewById(R.id.textView175);
        t175.setOnTouchListener(listener);
        t176 = (TextView)view.findViewById(R.id.textView176);
        t176.setOnTouchListener(listener);
        t177 = (TextView)view.findViewById(R.id.textView177);
        t177.setOnTouchListener(listener);
        t178 = (TextView)view.findViewById(R.id.textView178);
        t178.setOnTouchListener(listener);
        t179 = (TextView)view.findViewById(R.id.textView179);
        t179.setOnTouchListener(listener);
        t180 = (TextView)view.findViewById(R.id.textView180);
        t180.setOnTouchListener(listener);
        t181 = (TextView)view.findViewById(R.id.textView181);
        t181.setOnTouchListener(listener);
        t182 = (TextView)view.findViewById(R.id.textView182);
        t182.setOnTouchListener(listener);
        t183 = (TextView)view.findViewById(R.id.textView183);
        t183.setOnTouchListener(listener);
        t184 = (TextView)view.findViewById(R.id.textView184);
        t184.setOnTouchListener(listener);
        t185 = (TextView)view.findViewById(R.id.textView185);
        t185.setOnTouchListener(listener);
        t186 = (TextView)view.findViewById(R.id.textView186);
        t186.setOnTouchListener(listener);
        t187 = (TextView)view.findViewById(R.id.textView187);
        t187.setOnTouchListener(listener);
        t188 = (TextView)view.findViewById(R.id.textView188);
        t188.setOnTouchListener(listener);
        t189 = (TextView)view.findViewById(R.id.textView189);
        t189.setOnTouchListener(listener);
        t190 = (TextView)view.findViewById(R.id.textView190);
        t190.setOnTouchListener(listener);
        t191 = (TextView)view.findViewById(R.id.textView191);
        t191.setOnTouchListener(listener);
        t192 = (TextView)view.findViewById(R.id.textView192);
        t192.setOnTouchListener(listener);
        t193 = (TextView)view.findViewById(R.id.textView193);
        t193.setOnTouchListener(listener);
        t194 = (TextView)view.findViewById(R.id.textView194);
        t194.setOnTouchListener(listener);
        t195 = (TextView)view.findViewById(R.id.textView195);
        t195.setOnTouchListener(listener);
        t196 = (TextView)view.findViewById(R.id.textView196);
        t196.setOnTouchListener(listener);
        t197 = (TextView)view.findViewById(R.id.textView197);
        t197.setOnTouchListener(listener);
        t198 = (TextView)view.findViewById(R.id.textView198);
        t198.setOnTouchListener(listener);
        t199 = (TextView)view.findViewById(R.id.textView199);
        t199.setOnTouchListener(listener);
        t200 = (TextView)view.findViewById(R.id.textView200);
        t200.setOnTouchListener(listener);
        t201 = (TextView)view.findViewById(R.id.textView201);
        t201.setOnTouchListener(listener);
        t202 = (TextView)view.findViewById(R.id.textView202);
        t202.setOnTouchListener(listener);
        t203 = (TextView)view.findViewById(R.id.textView203);
        t203.setOnTouchListener(listener);
        t204 = (TextView)view.findViewById(R.id.textView204);
        t204.setOnTouchListener(listener);
        t205 = (TextView)view.findViewById(R.id.textView205);
        t205.setOnTouchListener(listener);
        t206 = (TextView)view.findViewById(R.id.textView206);
        t206.setOnTouchListener(listener);
        t207 = (TextView)view.findViewById(R.id.textView207);
        t207.setOnTouchListener(listener);
        return view;
    }
    private final View.OnTouchListener listener = new View.OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
            switch(event.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    if(flag){
                        int f = views.size()-1;
                        while (f>=0){
                            views.get(f).setBackgroundColor(Color.WHITE);
                            f--;
                        }
                        views.clear();
                        temp = "";
                        flag = false;
                    }
                    temp = temp+((TextView)v).getText();
                    int i = 0;
                    while(i<words.length){
                        boo=true;
                        int k = 0;
                        while((k<words[i].length())&&(k<temp.length())) {
                            if (temp.toLowerCase().charAt(k) != words[i].toLowerCase().charAt(k)) {
                                boo = false;
                            }
                            k++;
                        }
                        if(boo) {
                            if(temp.length()==words[i].length()) {
                                int j = 0;
                                View vi;
                                while (j<views.size()){
                                    vi = views.get(j);
                                    vi.setBackgroundColor(Color.GREEN);
                                    j++;
                                }
                                text.get(i).setBackgroundColor(Color.GREEN);
                            }
                            break;
                        }
                        i++;
                    }
                    if(boo&&(temp.length()==words[i].length())) {
                        views.add(v);
                        v.setBackgroundColor(Color.GREEN);
                        views.clear();
                        temp = "";
                    } else if(boo){
                        views.add(v);
                        v.setBackgroundColor(Color.YELLOW);
                    } else{
                        int l = views.size()-1;
                        while (l>=0){
                            views.get(l).setBackgroundColor(Color.RED);
                            l--;
                        }
                        flag = true;
                    }
                    break;
                case MotionEvent.ACTION_UP:
                    break;
                case MotionEvent.ACTION_MOVE:
                    v.setBackgroundColor(Color.YELLOW);
                    break;
            }
            return false;
        }
    };


}
